apiVersion: v1
kind: Pod
metadata:
  name: gogs
  labels:
    app: gogs
spec:
  containers:
    - name: gogs
      image: gogs/gogs:latest
      ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: gogs
  namespace: default
spec:
  selector:
    app: gogs
  type: NodePort
  ports:
  - name: gogs
    port: 3000
    protocol: TCP