apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: localhost:5000/hello:latest
        name: hello
        ports:
        - containerPort: 3000
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 0

---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  selector:
    app: hello
  type: NodePort
  ports:
  - name: registry
    port: 3000
    protocol: TCP